#!/usr/bin/env python3

from __future__ import annotations

import json
import posixpath
import re
from pathlib import Path

import yaml


ROOT_DIR = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT_DIR / "docs"
CONFIG_PATH = ROOT_DIR / "mkdocs.yml"
OUTPUT_PATH = DOCS_DIR / "complete-guide.md"
SECTIONS_PATH = DOCS_DIR / "assets" / "pdf-sections.json"
UNSET = object()

LINK_RE = re.compile(r'(!?\[[^\]]*\])\(([^)]+)\)')
GUIDE_OMIT_START = "<!-- complete-guide:omit:start -->"
GUIDE_OMIT_END = "<!-- complete-guide:omit:end -->"


INTRO = """<!-- This file is auto-generated by scripts/generate_complete_guide.py. -->

<style>
@page {
  size: A4;
  margin: 12mm;
}

html[data-pdf-mode="color"],
html[data-pdf-mode="color"] * {
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}

@media print {
  .md-header,
  .md-tabs,
  .md-sidebar,
  .md-footer,
  .md-top,
  .md-content__button,
  [data-md-component="toc"] {
    display: none !important;
  }

  .md-main__inner,
  .md-grid,
  .md-content {
    max-width: 100% !important;
    margin: 0 !important;
    padding: 0 !important;
  }

  .md-content__inner {
    border: 0 !important;
    box-shadow: none !important;
    margin: 0 !important;
    padding: 0 !important;
  }

  .md-typeset h1,
  .md-typeset h2,
  .md-typeset h3,
  .md-typeset h4 {
    page-break-after: avoid;
  }

  .md-typeset table:not([class]),
  .md-typeset pre,
  .md-typeset img,
  .md-typeset blockquote,
  .md-typeset details,
  .md-typeset .admonition {
    break-inside: avoid-page;
  }

  html[data-pdf-mode="paper"],
  html[data-pdf-mode="paper"] body,
  html[data-pdf-mode="paper"] .md-main,
  html[data-pdf-mode="paper"] .md-content,
  html[data-pdf-mode="paper"] .md-content__inner,
  html[data-pdf-mode="paper"] .md-typeset {
    background: #ffffff !important;
    color: #000000 !important;
    box-shadow: none !important;
  }

  html[data-pdf-mode="paper"] .md-typeset *,
  html[data-pdf-mode="paper"] .md-typeset p,
  html[data-pdf-mode="paper"] .md-typeset li,
  html[data-pdf-mode="paper"] .md-typeset td,
  html[data-pdf-mode="paper"] .md-typeset th,
  html[data-pdf-mode="paper"] .md-typeset blockquote,
  html[data-pdf-mode="paper"] .md-typeset code,
  html[data-pdf-mode="paper"] .md-typeset h1,
  html[data-pdf-mode="paper"] .md-typeset h2,
  html[data-pdf-mode="paper"] .md-typeset h3,
  html[data-pdf-mode="paper"] .md-typeset h4 {
    color: #000000 !important;
    text-shadow: none !important;
  }

  html[data-pdf-mode="paper"] .md-typeset a {
    color: #000000 !important;
    text-decoration: underline !important;
  }

  html[data-pdf-mode="paper"] .md-typeset .admonition,
  html[data-pdf-mode="paper"] .md-typeset details,
  html[data-pdf-mode="paper"] .md-typeset .admonition-title,
  html[data-pdf-mode="paper"] .md-typeset summary,
  html[data-pdf-mode="paper"] .md-typeset code,
  html[data-pdf-mode="paper"] .md-typeset table:not([class]),
  html[data-pdf-mode="paper"] .md-typeset th,
  html[data-pdf-mode="paper"] .md-typeset td,
  html[data-pdf-mode="paper"] .md-typeset blockquote {
    background: #ffffff !important;
    border-color: #000000 !important;
    box-shadow: none !important;
  }

  html[data-pdf-mode="paper"] .md-typeset img {
    filter: grayscale(100%);
  }
}
</style>

<script>
(() => {
  const SECTION_SELECTOR = '[data-pdf-section-group]';

  const parseSelection = () => {
    const raw = new URLSearchParams(window.location.search).get("sections");
    if (!raw) {
      return [];
    }

    return [...new Set(
      raw
        .split(",")
        .map((value) => value.trim().toLowerCase())
        .filter(Boolean)
    )];
  };

  const parseMode = () => {
    const mode = new URLSearchParams(window.location.search).get("mode");
    return mode === "paper" ? "paper" : "color";
  };

  const applySelection = (selected) => {
    if (!selected.length) {
      return;
    }

    const sections = Array.from(document.querySelectorAll(SECTION_SELECTOR));
    const selectedSet = new Set(selected);
    const labels = [];

    sections.forEach((section) => {
      const slug = section.dataset.pdfSectionGroup;
      const keep = selectedSet.has(slug);

      if (keep) {
        labels.push(section.dataset.pdfSectionTitle || slug);
      }

      section.hidden = !keep;
    });

    if (!labels.length) {
      return;
    }

    const title = document.querySelector(".md-typeset h1");
    if (!title) {
      return;
    }

    let note = document.getElementById("pdf-selection-summary");
    if (!note) {
      note = document.createElement("p");
      note.id = "pdf-selection-summary";
      note.style.margin = "0.75rem 0 1.25rem";
      note.style.padding = "0.85rem 1rem";
      note.style.border = "1px solid rgba(99, 91, 255, 0.2)";
      note.style.borderRadius = "0.8rem";
      note.style.background = "rgba(99, 91, 255, 0.08)";
      note.style.fontWeight = "600";
      title.insertAdjacentElement("afterend", note);
    }

    const modeLabel = parseMode() === "paper" ? "Paper-friendly" : "Color PDF";
    note.textContent = `Included in this PDF: ${labels.join(", ")} • ${modeLabel}`;
  };

  const applyMode = () => {
    document.documentElement.dataset.pdfMode = parseMode();
  };

  const triggerPrint = () => {
    window.setTimeout(() => window.print(), 500);
  };

  const init = () => {
    applyMode();
    applySelection(parseSelection());

    if (new URLSearchParams(window.location.search).get("download") === "1") {
      triggerPrint();
    }
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init, { once: true });
  } else {
    init();
  }
})();
</script>

# SOCAtlas Complete Guide
"""


def flatten_nav(items, section=None):
    entries = []

    for item in items:
        if not isinstance(item, dict):
            continue

        for title, value in item.items():
            if isinstance(value, str):
                entries.append((section, title, value))
            elif isinstance(value, list):
                entries.extend(flatten_nav(value, title))

    return entries


def slugify(value: str) -> str:
    lowered = value.lower()
    lowered = re.sub(r"[^\w\s-]", " ", lowered, flags=re.UNICODE)
    lowered = re.sub(r"[\s_-]+", "-", lowered).strip("-")
    return lowered or "section"


def build_section_index(entries):
    sections = []
    counts = {}
    titles = {}

    for section, _, _ in entries:
        label = "Start Here" if section is None else section
        slug = slugify(label)

        if slug not in counts:
            counts[slug] = 0
            titles[slug] = label
            sections.append({"slug": slug, "title": label, "count": 0})

        counts[slug] += 1

    for section in sections:
        section["count"] = counts[section["slug"]]
        section["title"] = titles[section["slug"]]

    return sections


def strip_first_h1_and_shift(content: str, shift: int) -> str:
    lines = content.splitlines()
    output = []
    in_fence = False
    removed_first_h1 = False

    for line in lines:
        stripped = line.lstrip()

        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            output.append(line)
            continue

        if not in_fence:
            match = re.match(r"^(#{1,6})\s+(.*)$", line)
            if match:
                level = len(match.group(1))
                text = match.group(2).strip()

                if level == 1 and not removed_first_h1:
                    removed_first_h1 = True
                    continue

                new_level = min(6, level + shift)
                output.append(f"{'#' * new_level} {text}")
                continue

        output.append(line)

    return "\n".join(output).strip()


def rewrite_target(source_path: str, target: str) -> str:
    if target.startswith(("http://", "https://", "mailto:", "#", "javascript:")):
        return target

    base, anchor = (target.split("#", 1) + [""])[:2]

    if not base:
        return target

    source_dir = posixpath.dirname(source_path)
    resolved = posixpath.normpath(posixpath.join(source_dir, base))

    if anchor:
        return f"{resolved}#{anchor}"

    return resolved


def rewrite_links(content: str, source_path: str) -> str:
    lines = content.splitlines()
    output = []
    in_fence = False

    for line in lines:
        stripped = line.lstrip()

        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            output.append(line)
            continue

        if in_fence:
            output.append(line)
            continue

        rewritten = LINK_RE.sub(
            lambda match: f"{match.group(1)}({rewrite_target(source_path, match.group(2).strip())})",
            line,
        )
        output.append(rewritten)

    return "\n".join(output)


def strip_marked_blocks(content: str) -> str:
    output = []
    in_block = False

    for line in content.splitlines():
        if line.strip() == GUIDE_OMIT_START:
            in_block = True
            continue

        if line.strip() == GUIDE_OMIT_END:
            in_block = False
            continue

        if not in_block:
            output.append(line)

    return "\n".join(output)


def strip_download_lines(content: str) -> str:
    filtered = []

    for line in content.splitlines():
        if "Download Full Guide PDF" in line:
            continue
        filtered.append(line)

    return "\n".join(filtered)


def generate():
    config = yaml.load(CONFIG_PATH.read_text(), Loader=yaml.BaseLoader)
    entries = flatten_nav(config.get("nav", []))
    sections = build_section_index(entries)

    parts = [INTRO.rstrip()]
    current_section = UNSET

    def open_section(section_name):
        label = "Start Here" if section_name is None else section_name
        slug = slugify(label)
        parts.append("")
        parts.append(
            f'<section class="pdf-guide-section" data-pdf-section-group="{slug}" data-pdf-section-title="{label}" markdown="1">'
        )
        parts.append("")
        parts.append(f"## {label}")

    def close_section():
        parts.append("")
        parts.append("</section>")

    for section, title, source in entries:
        if source == OUTPUT_PATH.name:
            continue

        source_path = DOCS_DIR / source
        content = source_path.read_text()
        content = rewrite_links(content, source)
        content = strip_marked_blocks(content)
        content = strip_download_lines(content)
        content = strip_first_h1_and_shift(content, shift=2)

        if section != current_section:
            if current_section is not UNSET:
                close_section()
            open_section(section)
            current_section = section

        parts.append("")
        parts.append(f"### {title}")
        parts.append("")
        parts.append(content)

    if current_section is not UNSET:
        close_section()

    OUTPUT_PATH.write_text("\n".join(parts).strip() + "\n")
    SECTIONS_PATH.write_text(json.dumps(sections, indent=2) + "\n")


if __name__ == "__main__":
    generate()
