#!/usr/bin/env python3

from __future__ import annotations

import json
import posixpath
import re
from pathlib import Path

import yaml


ROOT_DIR = Path(__file__).resolve().parents[1]
DOCS_DIR = ROOT_DIR / "docs"
CONFIG_PATH = ROOT_DIR / "mkdocs.yml"
OUTPUT_PATH = DOCS_DIR / "complete-guide.md"
SECTIONS_PATH = DOCS_DIR / "assets" / "pdf-sections.json"
UNSET = object()

LINK_RE = re.compile(r'(!?\[[^\]]*\])\(([^)]+)\)')
GUIDE_OMIT_START = "<!-- complete-guide:omit:start -->"
GUIDE_OMIT_END = "<!-- complete-guide:omit:end -->"


INTRO = """<!-- This file is auto-generated by scripts/generate_complete_guide.py. -->

<style>
@page {
  size: A4;
  margin: 12mm;
}

html[data-pdf-mode] body,
html[data-pdf-mode] .md-typeset,
html[data-pdf-mode] .md-typeset p,
html[data-pdf-mode] .md-typeset li,
html[data-pdf-mode] .md-typeset td,
html[data-pdf-mode] .md-typeset th,
html[data-pdf-mode] .md-typeset blockquote {
  font-family: "Inter", "Segoe UI", Arial, sans-serif !important;
}

html[data-pdf-mode] .md-typeset code,
html[data-pdf-mode] .md-typeset pre,
html[data-pdf-mode] .md-typeset pre code {
  font-family: "JetBrains Mono", "SFMono-Regular", Consolas, monospace !important;
}

html[data-pdf-mode="color"],
html[data-pdf-mode="color"] * {
  -webkit-print-color-adjust: exact;
  print-color-adjust: exact;
}

html[data-pdf-mode="paper"],
html[data-pdf-mode="paper"] * {
  -webkit-print-color-adjust: economy !important;
  print-color-adjust: economy !important;
  color-adjust: economy !important;
}

html[data-pdf-mode="paper"] {
  --md-primary-fg-color: #000000 !important;
  --md-primary-fg-color--light: #000000 !important;
  --md-primary-fg-color--dark: #000000 !important;
  --md-accent-fg-color: #000000 !important;
  --md-default-fg-color: #000000 !important;
  --md-default-fg-color--light: #111111 !important;
}

html[data-pdf-mode="paper"] body,
html[data-pdf-mode="paper"] .md-main,
html[data-pdf-mode="paper"] .md-content,
html[data-pdf-mode="paper"] .md-content__inner,
html[data-pdf-mode="paper"] .md-typeset {
  background: #ffffff !important;
  color: #000000 !important;
  box-shadow: none !important;
  background-image: none !important;
}

html[data-pdf-mode="paper"] .md-typeset *,
html[data-pdf-mode="paper"] .md-typeset p,
html[data-pdf-mode="paper"] .md-typeset li,
html[data-pdf-mode="paper"] .md-typeset td,
html[data-pdf-mode="paper"] .md-typeset th,
html[data-pdf-mode="paper"] .md-typeset blockquote,
html[data-pdf-mode="paper"] .md-typeset code,
html[data-pdf-mode="paper"] .md-typeset h1,
html[data-pdf-mode="paper"] .md-typeset h2,
html[data-pdf-mode="paper"] .md-typeset h3,
html[data-pdf-mode="paper"] .md-typeset h4 {
  color: #000000 !important;
  text-shadow: none !important;
  background-image: none !important;
}

html[data-pdf-mode="paper"] .md-typeset a {
  color: #000000 !important;
  text-decoration: underline !important;
}

html[data-pdf-mode="paper"] .md-typeset .admonition,
html[data-pdf-mode="paper"] .md-typeset details,
html[data-pdf-mode="paper"] .md-typeset .admonition-title,
html[data-pdf-mode="paper"] .md-typeset summary,
html[data-pdf-mode="paper"] .md-typeset code,
html[data-pdf-mode="paper"] .md-typeset pre,
html[data-pdf-mode="paper"] .md-typeset .highlight,
html[data-pdf-mode="paper"] .md-typeset .highlighttable,
html[data-pdf-mode="paper"] .md-typeset table:not([class]),
html[data-pdf-mode="paper"] .md-typeset th,
html[data-pdf-mode="paper"] .md-typeset td,
html[data-pdf-mode="paper"] .md-typeset blockquote,
html[data-pdf-mode="paper"] .pdf-guide-note {
  background: #ffffff !important;
  border-color: #000000 !important;
  box-shadow: none !important;
  color: #000000 !important;
  background-image: none !important;
}

html[data-pdf-mode="paper"] .md-typeset img,
html[data-pdf-mode="paper"] .md-typeset svg {
  filter: grayscale(100%) !important;
}

html[data-pdf-mode="paper"] .pdf-guide-note {
  color: #000000 !important;
}

html[data-pdf-export="download"] .md-main__inner,
html[data-pdf-export="download"] .md-grid,
html[data-pdf-export="download"] .md-content {
  max-width: 100% !important;
  margin: 0 !important;
  padding: 0 !important;
}

html[data-pdf-export="download"] .md-content__inner {
  border: 0 !important;
  box-shadow: none !important;
  margin: 0 !important;
  padding: 0 !important;
}

.pdf-guide-note {
  margin: 0.75rem 0 1.25rem;
  padding: 0.85rem 1rem;
  border-radius: 0.8rem;
  font-weight: 600;
}

.pdf-guide-note--selection {
  border: 1px solid rgba(99, 91, 255, 0.2);
  background: rgba(99, 91, 255, 0.08);
}

.pdf-guide-note--status {
  border: 1px solid rgba(10, 191, 83, 0.24);
  background: rgba(10, 191, 83, 0.08);
}

html[data-pdf-export="download"] .pdf-export-shell {
  position: fixed;
  top: 0;
  left: -100000px;
  width: 1200px;
  padding: 0;
  margin: 0;
  background: #ffffff;
  z-index: -1;
  pointer-events: none;
}

html[data-pdf-export="download"] .pdf-export-canvas,
html[data-pdf-export="download"] .pdf-export-canvas * {
  animation: none !important;
  transition: none !important;
}

html[data-pdf-export="download"] .pdf-export-canvas,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset p,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset li,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset td,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset th,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset blockquote {
  font-family: Arial, "Helvetica Neue", Helvetica, sans-serif !important;
  line-height: 1.55 !important;
}

html[data-pdf-export="download"] .pdf-export-canvas .md-typeset code,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset pre,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset pre code {
  font-family: "Courier New", Courier, monospace !important;
}

html[data-pdf-export="download"] .pdf-export-canvas,
html[data-pdf-export="download"] .pdf-export-canvas .md-content__inner {
  background: #ffffff !important;
}

html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset p,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset li,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset td,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset th,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset blockquote,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset h1,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset h2,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset h3,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset h4 {
  color: var(--md-default-fg-color) !important;
}

html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset a,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset a code {
  color: var(--md-typeset-a-color) !important;
}

html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset code,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset pre,
html[data-pdf-mode="color"][data-pdf-export="download"] .pdf-export-canvas .md-typeset pre code {
  color: var(--md-code-fg-color) !important;
}

html[data-pdf-export="download"] .pdf-export-canvas .md-typeset h1,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset h2,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset h3,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset h4 {
  line-height: 1.22 !important;
  letter-spacing: 0 !important;
}

html[data-pdf-export="download"] .pdf-export-canvas .md-typeset p,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset blockquote,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset pre,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset .admonition,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset details,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset img,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset h1,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset h2,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset h3,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset h4 {
  break-inside: avoid-page !important;
  page-break-inside: avoid !important;
}

html[data-pdf-export="download"] .pdf-export-canvas .md-typeset p,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset li,
html[data-pdf-export="download"] .pdf-export-canvas .md-typeset blockquote {
  orphans: 3;
  widows: 3;
}

@media print {
  .md-header,
  .md-tabs,
  .md-sidebar,
  .md-footer,
  .md-top,
  .md-content__button,
  [data-md-component="toc"] {
    display: none !important;
  }

  .md-main__inner,
  .md-grid,
  .md-content {
    max-width: 100% !important;
    margin: 0 !important;
    padding: 0 !important;
  }

  .md-content__inner {
    border: 0 !important;
    box-shadow: none !important;
    margin: 0 !important;
    padding: 0 !important;
  }

  .md-typeset h1,
  .md-typeset h2,
  .md-typeset h3,
  .md-typeset h4 {
    page-break-after: avoid;
  }

  .md-typeset table:not([class]),
  .md-typeset pre,
  .md-typeset img,
  .md-typeset blockquote,
  .md-typeset details,
  .md-typeset .admonition {
    break-inside: avoid-page;
  }

  html[data-pdf-export="download"] #pdf-download-status {
    display: none !important;
  }
}
</style>

<script>
(() => {
  const SECTION_SELECTOR = '[data-pdf-section-group]';
  const EMOJI_RE = /[\p{Extended_Pictographic}\uFE0F]/gu;

  const parseSelection = () => {
    const raw = new URLSearchParams(window.location.search).get("sections");
    if (!raw) {
      return [];
    }

    return [...new Set(
      raw
        .split(",")
        .map((value) => value.trim().toLowerCase())
        .filter(Boolean)
    )];
  };

  const parseMode = () => {
    const mode = new URLSearchParams(window.location.search).get("mode");
    return mode === "paper" ? "paper" : "color";
  };

  const parseImages = () =>
    new URLSearchParams(window.location.search).get("images") !== "0";

  const isDownloadRequested = () =>
    new URLSearchParams(window.location.search).get("download") === "1";

  const applySelection = (selected) => {
    if (!selected.length) {
      return;
    }

    const sections = Array.from(document.querySelectorAll(SECTION_SELECTOR));
    const selectedSet = new Set(selected);
    const labels = [];

    sections.forEach((section) => {
      const slug = section.dataset.pdfSectionGroup;
      const keep = selectedSet.has(slug);

      if (keep) {
        labels.push(section.dataset.pdfSectionTitle || slug);
      }

      section.hidden = !keep;
    });

    if (!labels.length) {
      return;
    }

    const title = document.querySelector(".md-typeset h1");
    if (!title) {
      return;
    }

    let note = document.getElementById("pdf-selection-summary");
    if (!note) {
      note = document.createElement("p");
      note.id = "pdf-selection-summary";
      note.className = "pdf-guide-note pdf-guide-note--selection";
      title.insertAdjacentElement("afterend", note);
    }

    const modeLabel = parseMode() === "paper" ? "Paper-friendly" : "Color PDF";
    const imagesLabel = parseImages() ? "With images" : "Text only";
    note.textContent = `Included in this PDF: ${labels.join(", ")} • ${modeLabel} • ${imagesLabel}`;
  };

  const applyMode = () => {
    document.documentElement.dataset.pdfMode = parseMode();
  };

  const applyImagePreference = () => {
    const includeImages = parseImages();
    document.documentElement.dataset.pdfImages = includeImages ? "on" : "off";

    if (includeImages) {
      return;
    }

    const seenFigures = new Set();
    document
      .querySelectorAll(".md-content__inner figure, .md-content__inner picture, .md-content__inner img, .md-content__inner svg")
      .forEach((node) => {
        const figure = node.closest("figure");
        if (figure && !seenFigures.has(figure)) {
          seenFigures.add(figure);
          figure.hidden = true;
          return;
        }

        node.hidden = true;
      });
  };

  const ensureStatusNote = () => {
    let note = document.getElementById("pdf-download-status");
    if (note) {
      return note;
    }

    const title = document.querySelector(".md-typeset h1");
    if (!title) {
      return null;
    }

    note = document.createElement("p");
    note.id = "pdf-download-status";
    note.className = "pdf-guide-note pdf-guide-note--status";
    note.setAttribute("data-html2canvas-ignore", "true");
    title.insertAdjacentElement("afterend", note);
    return note;
  };

  const setStatus = (message) => {
    const note = ensureStatusNote();
    if (note) {
      note.textContent = message;
    }
  };

  const buildFilename = () => {
    const selected = parseSelection();
    const mode = parseMode();
    const imagesSuffix = parseImages() ? "" : "-no-images";

    if (!selected.length) {
      return `socatlas-complete-guide-${mode}${imagesSuffix}.pdf`;
    }

    if (selected.length <= 2) {
      return `socatlas-${selected.join("-")}-${mode}${imagesSuffix}.pdf`;
    }

    return `socatlas-${selected[0]}-${selected.length}-sections-${mode}${imagesSuffix}.pdf`;
  };

  const prepareDownloadTitle = () => {
    const previousTitle = document.title;
    document.title = buildFilename().replace(/\.pdf$/i, "");

    return () => {
      document.title = previousTitle;
    };
  };

  const stripEmoji = (value) =>
    value.replace(EMOJI_RE, "").replace(/\s{2,}/g, " ").trim();

  const triggerPrint = () => {
    window.setTimeout(() => window.print(), 250);
  };

  const waitForFonts = async () => {
    if (document.fonts && document.fonts.ready) {
      await document.fonts.ready;
    }
  };

  const waitForImages = async () => {
    if (!parseImages()) {
      return;
    }

    const images = Array.from(document.querySelectorAll(".md-content__inner img"));
    await Promise.all(
      images.map(
        (image) =>
          new Promise((resolve) => {
            if (image.complete) {
              resolve();
              return;
            }

            image.addEventListener("load", resolve, { once: true });
            image.addEventListener("error", resolve, { once: true });
          })
      )
    );
  };

  const waitForLayout = () =>
    new Promise((resolve) => {
      requestAnimationFrame(() => {
        requestAnimationFrame(resolve);
      });
    });

  const prepareExportState = () => {
    const body = document.body;
    const html = document.documentElement;
    const snapshot = {
      bodyScheme: body.getAttribute("data-md-color-scheme"),
      bodyPrimary: body.getAttribute("data-md-color-primary"),
      bodyAccent: body.getAttribute("data-md-color-accent"),
      bodyColorScheme: body.style.colorScheme,
      htmlColorScheme: html.style.colorScheme,
      bodyBackground: body.style.background,
      bodyColor: body.style.color,
    };
    const mode = parseMode();
    const defaultText =
      mode === "paper" ? "#000000" : "rgba(0, 0, 0, 0.87)";
    const primary = mode === "paper" ? "black" : (snapshot.bodyPrimary || "teal");
    const accent = mode === "paper" ? "black" : (snapshot.bodyAccent || "indigo");

    body.setAttribute("data-md-color-scheme", "default");
    body.setAttribute("data-md-color-primary", primary);
    body.setAttribute("data-md-color-accent", accent);
    body.style.colorScheme = "light";
    html.style.colorScheme = "light";
    body.style.background = "#ffffff";
    body.style.color = defaultText;

    return () => {
      if (snapshot.bodyScheme === null) {
        body.removeAttribute("data-md-color-scheme");
      } else {
        body.setAttribute("data-md-color-scheme", snapshot.bodyScheme);
      }

      if (snapshot.bodyPrimary === null) {
        body.removeAttribute("data-md-color-primary");
      } else {
        body.setAttribute("data-md-color-primary", snapshot.bodyPrimary);
      }

      if (snapshot.bodyAccent === null) {
        body.removeAttribute("data-md-color-accent");
      } else {
        body.setAttribute("data-md-color-accent", snapshot.bodyAccent);
      }

      body.style.colorScheme = snapshot.bodyColorScheme;
      html.style.colorScheme = snapshot.htmlColorScheme;
      body.style.background = snapshot.bodyBackground;
      body.style.color = snapshot.bodyColor;
    };
  };

  const triggerDownload = async () => {
    let restoreExportState = () => {};
    let restoreTitle = () => {};
    let cleanedUp = false;
    const cleanup = () => {
      if (cleanedUp) {
        return;
      }

      cleanedUp = true;
      restoreExportState();
      restoreTitle();
      delete document.documentElement.dataset.pdfExport;
    };

    try {
      setStatus(
        parseMode() === "paper"
          ? "Opening Chrome print dialog with paper-friendly styling. Turn off Background graphics in Chrome for the cleanest result."
          : "Opening Chrome print dialog. Choose Save as PDF and keep Background graphics on for the richest color output."
      );
      document.documentElement.dataset.pdfExport = "download";
      restoreExportState = prepareExportState();
      restoreTitle = prepareDownloadTitle();
      window.scrollTo({ top: 0, left: 0, behavior: "auto" });
      await waitForLayout();
      await waitForFonts();
      await waitForImages();
      await waitForLayout();
      window.addEventListener("afterprint", () => {
        cleanup();
        setStatus("Print dialog closed. If nothing saved yet, open Download as PDF again and choose Save as PDF in Chrome.");
      }, { once: true });
      triggerPrint();
    } catch (error) {
      cleanup();
      console.error(error);
      setStatus("Could not open the Chrome print dialog. Press Ctrl/Cmd+P to save as PDF.");
    }
  };

  const init = () => {
    applyMode();
    applySelection(parseSelection());
    applyImagePreference();

    if (isDownloadRequested()) {
      window.setTimeout(() => {
        triggerDownload();
      }, 350);
    }
  };

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init, { once: true });
  } else {
    init();
  }
})();
</script>

# SOCAtlas Complete Guide
"""


def flatten_nav(items, section=None):
    entries = []

    for item in items:
        if not isinstance(item, dict):
            continue

        for title, value in item.items():
            if isinstance(value, str):
                entries.append((section, title, value))
            elif isinstance(value, list):
                entries.extend(flatten_nav(value, title))

    return entries


def slugify(value: str) -> str:
    lowered = value.lower()
    lowered = re.sub(r"[^\w\s-]", " ", lowered, flags=re.UNICODE)
    lowered = re.sub(r"[\s_-]+", "-", lowered).strip("-")
    return lowered or "section"


def build_section_index(entries):
    sections = []
    counts = {}
    titles = {}

    for section, _, _ in entries:
        label = "Start Here" if section is None else section
        slug = slugify(label)

        if slug not in counts:
            counts[slug] = 0
            titles[slug] = label
            sections.append({"slug": slug, "title": label, "count": 0})

        counts[slug] += 1

    for section in sections:
        section["count"] = counts[section["slug"]]
        section["title"] = titles[section["slug"]]

    return sections


def build_page_anchor_map(entries):
    anchors = {}
    used = set()

    for _, _, source in entries:
        normalized = posixpath.normpath(source)
        base_anchor = f"guide-page-{slugify(posixpath.splitext(normalized)[0].replace('/', '-'))}"
        anchor = base_anchor
        suffix = 2

        while anchor in used:
            anchor = f"{base_anchor}-{suffix}"
            suffix += 1

        anchors[normalized] = anchor
        used.add(anchor)

    return anchors


def build_section_anchor_map(entries):
    anchors = {}

    for section, _, source in entries:
        normalized = posixpath.normpath(source)
        prefix = normalized.split("/", 1)[0] if "/" in normalized else ""
        if not prefix:
            continue

        label = "Start Here" if section is None else section
        anchors[prefix] = f"guide-section-{slugify(label)}"

    return anchors


def strip_first_h1_and_shift(content: str, shift: int) -> str:
    lines = content.splitlines()
    output = []
    in_fence = False
    removed_first_h1 = False

    for line in lines:
        stripped = line.lstrip()

        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            output.append(line)
            continue

        if not in_fence:
            match = re.match(r"^(#{1,6})\s+(.*)$", line)
            if match:
                level = len(match.group(1))
                text = match.group(2).strip()

                if level == 1 and not removed_first_h1:
                    removed_first_h1 = True
                    continue

                new_level = min(6, level + shift)
                output.append(f"{'#' * new_level} {text}")
                continue

        output.append(line)

    return "\n".join(output).strip()


def rewrite_target(
    source_path: str,
    target: str,
    page_anchors: dict[str, str],
    section_anchors: dict[str, str],
) -> str:
    if target.startswith(("http://", "https://", "mailto:", "#", "javascript:")):
        return target

    base, anchor = (target.split("#", 1) + [""])[:2]

    if not base:
        return target

    source_dir = posixpath.dirname(source_path)
    resolved = posixpath.normpath(posixpath.join(source_dir, base))

    if resolved in page_anchors:
        return f"#{page_anchors[resolved]}"

    prefix = resolved.split("/", 1)[0] if "/" in resolved else ""
    if prefix and prefix in section_anchors and resolved.endswith((".md", ".html")):
        return f"#{section_anchors[prefix]}"

    if anchor:
        return f"{resolved}#{anchor}"

    return resolved


def rewrite_links(
    content: str,
    source_path: str,
    page_anchors: dict[str, str],
    section_anchors: dict[str, str],
) -> str:
    lines = content.splitlines()
    output = []
    in_fence = False

    for line in lines:
        stripped = line.lstrip()

        if stripped.startswith("```") or stripped.startswith("~~~"):
            in_fence = not in_fence
            output.append(line)
            continue

        if in_fence:
            output.append(line)
            continue

        rewritten = LINK_RE.sub(
            lambda match: f"{match.group(1)}({rewrite_target(source_path, match.group(2).strip(), page_anchors, section_anchors)})",
            line,
        )
        output.append(rewritten)

    return "\n".join(output)


def strip_marked_blocks(content: str) -> str:
    output = []
    in_block = False

    for line in content.splitlines():
        if line.strip() == GUIDE_OMIT_START:
            in_block = True
            continue

        if line.strip() == GUIDE_OMIT_END:
            in_block = False
            continue

        if not in_block:
            output.append(line)

    return "\n".join(output)


def strip_download_lines(content: str) -> str:
    filtered = []

    for line in content.splitlines():
        if "Download Full Guide PDF" in line:
            continue
        filtered.append(line)

    return "\n".join(filtered)


def generate_question_bank():
    questions = []
    quick_dir = DOCS_DIR / "quick"
    if not quick_dir.exists():
        return
    
    for md_file in quick_dir.glob("*.md"):
        content = md_file.read_text()
        lines = content.splitlines()
        for line in lines:
            if line.strip().startswith('|') and '|' in line:
                cells = [c.strip() for c in line.split('|')]
                # Expected row: ['', '1', 'Concept', 'Answer', 'Example', '']
                if len(cells) >= 5 and cells[1].isdigit():
                    questions.append({
                        "id": int(cells[1]),
                        "concept": cells[2],
                        "answer": cells[3],
                        "example": cells[4],
                        "category": md_file.stem.replace('_', ' ').title()
                    })
    
    bank_path = DOCS_DIR / "assets" / "questions-bank.json"
    bank_path.write_text(json.dumps(questions, indent=2) + "\n")


def generate():
    config = yaml.load(CONFIG_PATH.read_text(), Loader=yaml.BaseLoader)
    entries = flatten_nav(config.get("nav", []))
    sections = build_section_index(entries)
    page_anchors = build_page_anchor_map(entries)
    section_anchors = build_section_anchor_map(entries)

    parts = [INTRO.rstrip()]
    current_section = UNSET

    def open_section(section_name):
        label = "Start Here" if section_name is None else section_name
        slug = slugify(label)
        parts.append("")
        parts.append(
            f'<section class="pdf-guide-section" data-pdf-section-group="{slug}" data-pdf-section-title="{label}" markdown="1">'
        )
        parts.append("")
        parts.append(f'<div id="guide-section-{slug}"></div>')
        parts.append("")
        parts.append(f"## {label}")

    def close_section():
        parts.append("")
        parts.append("</section>")

    for section, title, source in entries:
        if source == "complete-guide.md":
            continue

        source_path = DOCS_DIR / source
        if not source_path.exists():
            continue

        content = source_path.read_text()
        content = rewrite_links(content, source, page_anchors, section_anchors)
        content = strip_marked_blocks(content)
        content = strip_download_lines(content)
        content = strip_first_h1_and_shift(content, shift=2)

        if section != current_section:
            if current_section is not UNSET:
                close_section()
            open_section(section)
            current_section = section

        parts.append("")
        parts.append(f'<div id="{page_anchors[posixpath.normpath(source)]}"></div>')
        parts.append("")
        parts.append(f"### {title}")
        parts.append("")
        parts.append(content)

    if current_section is not UNSET:
        close_section()

    OUTPUT_PATH.write_text("\n".join(parts).strip() + "\n")
    SECTIONS_PATH.write_text(json.dumps(sections, indent=2) + "\n")
    generate_question_bank()


if __name__ == "__main__":
    generate()
